Updated Readme.md
XenonIO/cybersecurity pull request #11
Opened 2020-02-07 17:41 UTC by gdh13

minor updates; is AccountDock one of our companies?

2020-02-17 00:53 UTC, usiegj00 requested changes
Fix date and it's approved.

2020-02-17 00:53 UTC, usiegj00 commented on README.md
> +Copyright Jonathan Siegel, 2018-2010. Please contact cyber@xenon.io if you would like to re-use or contribute to this plan.
Typo

2020-02-17 18:05 UTC, gdh13 commented
Complete

2020-02-17 21:27 UTC, gdh13 commented
Corrections made; ready for approval

2020-02-17 22:02 UTC, usiegj00 approved these changes

2020-02-18 21:50 UTC, usiegj00 approved these changes
👍

2023-01-02 18:54 UTC, closed without merging